export {default as Header} from './Header'
export {default as Main} from './Main'
export {default as About} from './About'
export {default as Servise} from './Servise'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'
